### ISSUE TITLE
Dangerous on Production

### ISSUE THREAD

**Issue by Nicholas-Westby** [rsoeteman/umbraco-admin-reset#2]
Just an observation that this could be dangerous if anybody uses it on a production environment. It temporarily allows anybody who knows the password ("Admin1234!") to login.

It might be worthwhile to make this password configurable. Some ways to accomplish this would be to add a web.config key or to add a text file in the bin folder that contains the new password.

**Comment by rsoeteman** [comment]
Hi,

Thank you for your email, I am currently out of the office without internet connection for this week (Until friday 13th). 

I am really sorry if your email is urgent, but follow up next weekend.

Best regards,

Richard Soeteman
Soeteman Software

Quality Umbraco packages | http://www.soetemansoftware.nl

**Comment by sniffdk** [comment]
Haha Richard, did you miss this one because of the auto-reply? :smile:

**Comment by rsoeteman** [comment]
No but it's not an issue since you can change the password.


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: Mads Krohn <notifications@github.com> 
Datum: 21-07-2016  23:28  (GMT+01:00) 
Aan: rsoeteman/umbraco-admin-reset <umbraco-admin-reset@noreply.github.com> 
Cc: Richard Soeteman <richard@soetemansoftware.nl>, Comment <comment@noreply.github.com> 
Onderwerp: Re: [rsoeteman/umbraco-admin-reset] Dangerous on Production (#2) 

Haha Richard, did you miss this one because of the auto-reply? 😄

**Comment by Nicholas-Westby** [comment]
Pull request submitted: https://github.com/rsoeteman/umbraco-admin-reset/pull/3

**Comment by Nicholas-Westby** [comment]
Since this was merged in, I'll close this issue.
